spring:
  datasource:
    url: jdbc:postgresql://dev-postgres:5432/userdb
    username: ${USER_DB_USERNAME:user_service}
    password: ${USER_DB_PASSWORD:user_pass}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com.example.microservices.user: INFO
